### ISSUE TITLE
Too many repeated crosslinks?

### ISSUE THREAD

**Issue by martingraham** [Rappsilber-Laboratory/CLMS-UI#35] opened 2016-06-09 11:31 UTC
Don't know if this is from the new database or not...

..and don't know if this is me misinterpreting data after a while away from it, but ...

On Search:3927 (polii, 12 proteins), if I look at the cross links of Protein Rpb-11, I find things like an ambiguous crosslink that has 20 matches.

This crosslink (Rpb1_644-Rpb11_26) is then repeated 20 times in the protein's crosslink list, always with the same matches (see it in the list below) - same for other links seemingly depending on how many matches are involved in each crosslink

temp1 is the protein object for rpb-11:

temp1.crossLinks.forEach(function(xlink) { var mids = xlink.matches.map(function(match) { return match[0].id; }); console.log ("xlink", xlink.id, JSON.stringify(mids)); })

```
2VM1090:1 xlink Rpb1_644-Rpb11_26 ["227084896","227085496","227082240","227085250","227086379","227089496","227084980","227100560","227085363","227100913","227085135","227086057","227088720","227081619","227085840","227085499","227086367","227087653","227087521","227088199"]
4VM1090:1 xlink Rpb11_55-Rpb11_88 ["227083287","227080563","227086450","227083315","227088352","227100279","227085609","227081298","227081742","227081366"]
VM1090:1 xlink Rpb1_644-Rpb11_26 ["227084896","227085496","227082240","227085250","227086379","227089496","227084980","227100560","227085363","227100913","227085135","227086057","227088720","227081619","227085840","227085499","227086367","227087653","227087521","227088199"]
6VM1090:1 xlink Rpb11_55-Rpb11_88 ["227083287","227080563","227086450","227083315","227088352","227100279","227085609","227081298","227081742","227081366"]
7VM1090:1 xlink Rpb1_644-Rpb11_26 ["227084896","227085496","227082240","227085250","227086379","227089496","227084980","227100560","227085363","227100913","227085135","227086057","227088720","227081619","227085840","227085499","227086367","227087653","227087521","227088199"]
2VM1090:1 xlink Rpb11_55-Rpb11_88 ["227083287","227080563","227086450","227083315","227088352","227100279","227085609","227081298","227081742","227081366"]
2VM1090:1 xlink Rpb1_644-Rpb11_26 ["227084896","227085496","227082240","227085250","227086379","227089496","227084980","227100560","227085363","227100913","227085135","227086057","227088720","227081619","227085840","227085499","227086367","227087653","227087521","227088199"]
2VM1090:1 xlink Rpb11_55-Rpb11_88 ["227083287","227080563","227086450","227083315","227088352","227100279","227085609","227081298","227081742","227081366"]
2VM1090:1 xlink Rpb1_644-Rpb11_26 ["227084896","227085496","227082240","227085250","227086379","227089496","227084980","227100560","227085363","227100913","227085135","227086057","227088720","227081619","227085840","227085499","227086367","227087653","227087521","227088199"]
2VM1090:1 xlink Rpb11_20-Rpb11_37 ["227085010","227084770"]
4VM1090:1 xlink Rpb11_55-Rpb11_88 ["227083287","227080563","227086450","227083315","227088352","227100279","227085609","227081298","227081742","227081366"]
5VM1090:1 xlink Rpb1_644-Rpb11_26 ["227084896","227085496","227082240","227085250","227086379","227089496","227084980","227100560","227085363","227100913","227085135","227086057","227088720","227081619","227085840","227085499","227086367","227087653","227087521","227088199"]
2VM1090:1 xlink Rpb11_55-Rpb11_88 ["227083287","227080563","227086450","227083315","227088352","227100279","227085609","227081298","227081742","227081366"]
2VM1090:1 xlink Rpb11_20-Rpb11_37 ["227085010","227084770"]
2VM1090:1 xlink Rpb11_55-Rpb11_93 ["227082724"]
VM1090:1 xlink Rpb1_644-Rpb11_26 ["227084896","227085496","227082240","227085250","227086379","227089496","227084980","227100560","227085363","227100913","227085135","227086057","227088720","227081619","227085840","227085499","227086367","227087653","227087521","227088199"]
```

**Comment by colin-combe** [comment] 2016-06-09 12:39
> Don't know if this is from the new database or not...
>

Shouldn't be as you're not using the new database? And I think you 
haven't pulled any changes to do with the move to new database.

Also, the problem is present in the deployed version I think 
(http://sce-bio-c01758.bio.ed.ac.uk/xi3/network.php?sid=3927-55657-30909-90497-50665).

I'm going to give you a quick call. If I don't get you we can look at 
this tomorrow.

c


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment] 2016-06-09 12:48
the problem seems slightly different in deployed version,
they are repeated only twice,
once with id: "Rpb1_644-Rpb11_26"
once with id: "Rpb1 644-Rpb11 26"


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment] 2016-06-09 13:28
Above comment false, was exactly the same in deployed version, depended on whether you looked at Rpb1 or Rpb11.

Its a stupid mistake in the model, a consequence of how this code was originally hacked out of xiNET (making excuses for self).

Fix is here:  https://github.com/colin-combe/CLMS-model/commit/ac2a9d4ce7a0a2483655139ee8397b75a2613360

You can get it by pulling from my 'repition_bug_fix' branch.

note: I'm still mystified about whats causing:

> once with id: "Rpb1_644-Rpb11_26" 
> once with id: "Rpb1 644-Rpb11 26"

will continue to look for it. You'd think it'd be easy to find...

**Comment by colin-combe** [comment] 2016-06-09 14:06
> note: I'm still mystified about whats causing:
> 
>     once with id: "Rpb1_644-Rpb11_26"
>     once with id: "Rpb1 644-Rpb11 26

There were no cross-links with absent underscores in their IDs - it just looked that way in debugger. There was a further silly error - for self links (same protein at both ends) the crossLink was getting added to protein twice.

Fix was this:  https://github.com/colin-combe/CLMS-model/commit/615c6622b01027ef3497bf2d736907280c7bac8f

Again, you can get it by pulling from my CLMS-model repetition_bug_fix branch.

I tidied up the code in the model quite a bit this week, should have less problems like this in future  (but don't pull from my CLMS-model master branch yet - it'll break things at mo').

Closing.

**Closed by colin-combe** 2016-06-09 14:06 UTC

**Comment by martingraham** [comment] 2016-06-09 14:39
Cheers Colin, 

me

**Comment by colin-combe** [comment] 2016-06-09 15:17
Yeah - my codes in a pretty bad state in places. Good catch spotting the 
mistake(s). We'll get it all tidied up eventually... ;)

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by martingraham** [comment] 2016-06-10 08:46
The Chrome developers keep getting told about that disappearing underscore bug (it's to dom with they cant keep the line height consistent) but keep ignoring it or closing it. One of the complainants may have a familiar email -->

https://bugs.chromium.org/p/chromium/issues/detail?id=473028
https://bugs.chromium.org/p/chromium/issues/detail?id=420714
https://bugs.chromium.org/p/chromium/issues/detail?id=532471
https://bugs.chromium.org/p/chromium/issues/detail?id=41457
